# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#Pay.create([{code: "cmr",nom: "Cameroun"},{code: "fr",nom: "France"},{code: "all",nom: "Allemagne"}])
#cmr=Pay.find_by_code("cmr")
#Ville.create([{code: "dla",nom: "Douala",pay_id: cmr.id},{code: "yde",nom: "Yaoundé",pay_id: cmr.id},{code: "baff",nom: "Baffoussam",pay_id: cmr.id}])

#add country
[ "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua & Deps",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Rep",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo {Democratic Rep}",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland {Republic}",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea North",
  "Korea South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Montenegro",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Mozambique",
  "Myanmar, {Burma}",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "St Kitts & Nevis",
  "St Lucia",
  "Saint Vincent & the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuea",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Palestine"].each do |param|
  Pay.find_or_create_by_nom(param)
end


[["admin","possède tous les droits sur le système"],
  ["vente_controle","controlle total sur les commandes"],
  ["vente_view","voir les commandes et imprimer les factures"],
  ["achat_controle","controlle total sur les aprovisionement"],
  ["achat_view","voir les achat et imprimer les etat"],
  ["categories_controle","controlle total sur les categories de droit"],
  ["categories_view","voir les différents catégories de droit"],
  ["clients_controle","controlle total sur les client"],
  ["clients_view","voir les cleint"],
  ["options_controle","controlle total sur les configurations"],
  ["droits_controle","controlle total sur les droits"],
  ["factures_controle","controlle total sur les facture"],
  ["fournisseurs_controle","controlle total sur les fournisseurs"],
  ["fournisseurs_view","controlle total sur les aprovisionement"],
  ["groupes_controle","controlle total sur les groupes"],
  ["groupe_view","voir les groupe"],
  ["produits_controle","controlle total sur les produits"],
  ["produits_view","voir les produits"],
  ["rayons_controle","controlle total sur les rayons"],
  ["rayons_view","voir les rayons"],
  ["type_produits_controle","controlle total sur les catégories de produits"],
  ["type_produits_view","voir les categories de produits"],
  ["coordonne_bancaire_controle","controle total sur les coordonnées bancaires"]].each do |param|
  if Category.first.nil?
    Category.find_or_create_by_code_and_nom_and_description("CG0000001",param[0],param[1]) 
  else
    old_code = Category.last.code[-7..-1]
    code="CG"+old_code.next
    Category.find_or_create_by_code_and_nom_and_description(code,param[0],param[1]) 
  end
  
end

Groupe.create(:nom=>"admin",:code=>"GR0000001",:description=>"groupe des administrateur",:is_active=>1)

User.create(:compte=>"admin@admin.cm",:nom=>"admin",:prenom=>"admin",:groupe_id=>Groupe.first.id,:passe=>Digest::SHA1.hexdigest("admin"),:is_admin=>1)

Client.create(:nom=>"autre",:code=>"CL0000001",:address=>"autre",:phone=>"655206994",:pay_id=>1,:ville=>"Douala")

GroupeCategorie.create(:groupe_id=>Groupe.first.id,:category_id=>Category.first.id)
